# This file was generated by GoReleaser. DO NOT EDIT.
cask "podspawn" do
  name "podspawn"
  desc "Ephemeral SSH dev containers via native sshd"
  homepage "https://podspawn.dev"
  version "0.4.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "podspawn"

  on_macos do
    on_intel do
      url "https://github.com/podspawn/podspawn/releases/download/v#{version}/podspawn_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/podspawn/podspawn"
      sha256 "f21071c97a49ec496f4fd2472c9c557fba2f37dbd02cd2bf0127e5506151f542"
    end
    on_arm do
      url "https://github.com/podspawn/podspawn/releases/download/v#{version}/podspawn_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/podspawn/podspawn"
      sha256 "025e4f87d2e8775a579921e9ab77b03d67120e939afccdf7a1b7f94ec8b42fe5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/podspawn/podspawn/releases/download/v#{version}/podspawn_#{version}_linux_amd64.tar.gz",
        verified: "github.com/podspawn/podspawn"
      sha256 "9ee5c4aed8b5bebfd09202755d88469112db9a1b75509994b49b33c69c3457f7"
    end
    on_arm do
      url "https://github.com/podspawn/podspawn/releases/download/v#{version}/podspawn_#{version}_linux_arm64.tar.gz",
        verified: "github.com/podspawn/podspawn"
      sha256 "27d5e51594d547948701e50d823fdff42217a1253292cc2f13aff2bd3edf4525"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/podspawn"]
    end
  end

  # No zap stanza required
end
