# This file was generated by GoReleaser. DO NOT EDIT.
cask "podspawn" do
  name "podspawn"
  desc "Ephemeral SSH dev containers via native sshd"
  homepage "https://podspawn.dev"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "podspawn"

  on_macos do
    on_intel do
      url "https://github.com/podspawn/podspawn/releases/download/v#{version}/podspawn_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/podspawn/podspawn"
      sha256 "76191069406c801c698d7e278dd5458ff6f69c0fa45fde5c65652a658922613c"
    end
    on_arm do
      url "https://github.com/podspawn/podspawn/releases/download/v#{version}/podspawn_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/podspawn/podspawn"
      sha256 "f8a33ea3120724f90eee5add92e0be70b6fe87def0dfc306e86e6e9cf6686673"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/podspawn/podspawn/releases/download/v#{version}/podspawn_#{version}_linux_amd64.tar.gz",
        verified: "github.com/podspawn/podspawn"
      sha256 "b8145c4f6c4462bda17ac2364f5ebd879942b7620ec04382a617b90c733beb2f"
    end
    on_arm do
      url "https://github.com/podspawn/podspawn/releases/download/v#{version}/podspawn_#{version}_linux_arm64.tar.gz",
        verified: "github.com/podspawn/podspawn"
      sha256 "3021cfdc73515d53d668c45a87dda0714c14e434cb5b1f2d549bffbff58bd4ca"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/podspawn"]
    end
  end

  # No zap stanza required
end
