# This file was generated by GoReleaser. DO NOT EDIT.
cask "podspawn" do
  name "podspawn"
  desc "Ephemeral SSH dev containers via native sshd"
  homepage "https://podspawn.dev"
  version "0.3.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "podspawn"

  on_macos do
    on_intel do
      url "https://github.com/podspawn/podspawn/releases/download/v#{version}/podspawn_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/podspawn/podspawn"
      sha256 "42ef8205098b016272727a190b142633512f1939f971695ed7d8779db01736f3"
    end
    on_arm do
      url "https://github.com/podspawn/podspawn/releases/download/v#{version}/podspawn_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/podspawn/podspawn"
      sha256 "194c75bced86c79e09356900953a224b1c4804fac294b099d5b10a5e1406038d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/podspawn/podspawn/releases/download/v#{version}/podspawn_#{version}_linux_amd64.tar.gz",
        verified: "github.com/podspawn/podspawn"
      sha256 "7c18411ff9a1024388d932359fe980d128a3beb583648331281685eb385d5f8a"
    end
    on_arm do
      url "https://github.com/podspawn/podspawn/releases/download/v#{version}/podspawn_#{version}_linux_arm64.tar.gz",
        verified: "github.com/podspawn/podspawn"
      sha256 "f91c7f997c63769dfebfca3d0ba09f6b58e3d3fb57f1c298016835f967ca7704"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/podspawn"]
    end
  end

  # No zap stanza required
end
