# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Podspawn < Formula
  desc "Ephemeral SSH dev containers via native sshd"
  homepage "https://github.com/podspawn/podspawn"
  version "0.2.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/podspawn/podspawn/releases/download/v0.2.0/podspawn_0.2.0_darwin_amd64.tar.gz"
      sha256 "71f8d8ee0b7d536cd8e4ae6a58ccbe76d47602970568781e78636614b6bc593d"

      define_method(:install) do
        bin.install "podspawn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/podspawn/podspawn/releases/download/v0.2.0/podspawn_0.2.0_darwin_arm64.tar.gz"
      sha256 "c8b93dedce49021a976da68ce4d8ae5c452c82bae0647757b76599552fa00c32"

      define_method(:install) do
        bin.install "podspawn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/podspawn/podspawn/releases/download/v0.2.0/podspawn_0.2.0_linux_amd64.tar.gz"
      sha256 "1a798abf3d9f33ab84daf00822ae55b23757e455fb9c0e12a8ef347669fbbaf3"
      define_method(:install) do
        bin.install "podspawn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/podspawn/podspawn/releases/download/v0.2.0/podspawn_0.2.0_linux_arm64.tar.gz"
      sha256 "c4f4801ee613941a6db2e91ac03672d82269169a27eb5ae1145d615d229d9858"
      define_method(:install) do
        bin.install "podspawn"
      end
    end
  end

  test do
    system "#{bin}/podspawn", "version"
  end
end
