# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Podspawn < Formula
  desc "Ephemeral SSH dev containers via native sshd"
  homepage "https://github.com/podspawn/podspawn"
  version "0.1.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/podspawn/podspawn/releases/download/v0.1.0/podspawn_0.1.0_darwin_amd64.tar.gz"
      sha256 "9080582e640b8d40dfc8670b9ee2f5414d4c0acaf90902d9137b4928fa4df461"

      define_method(:install) do
        bin.install "podspawn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/podspawn/podspawn/releases/download/v0.1.0/podspawn_0.1.0_darwin_arm64.tar.gz"
      sha256 "c3894145e343fd72842c82bd8121cd1ce8da565f6ddf2a540c6622ee46a93e4d"

      define_method(:install) do
        bin.install "podspawn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/podspawn/podspawn/releases/download/v0.1.0/podspawn_0.1.0_linux_amd64.tar.gz"
      sha256 "9483d9a961a15bfe5a3efe7f81314fb13579ec61642c7f9b910238530c7790d8"
      define_method(:install) do
        bin.install "podspawn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/podspawn/podspawn/releases/download/v0.1.0/podspawn_0.1.0_linux_arm64.tar.gz"
      sha256 "6b747a915b6936ae279b70044a7134fd166a73a6d43cdc841ff2e7a596e670f0"
      define_method(:install) do
        bin.install "podspawn"
      end
    end
  end

  test do
    system "#{bin}/podspawn", "version"
  end
end
